- arctic_training/__init__.py
- arctic_training/callback/__init__.py
- arctic_training/checkpoint/__init__.py
- arctic_training/config/__init__.py
- arctic_training/data/__init__.py
- arctic_training/model/__init__.py
- arctic_training/optimizer/__init__.py
- arctic_training/scheduler/__init__.py
- arctic_training/tokenizer/__init__.py
- arctic_training/trainer/__init__.py
- projects/mlp_speculator/train.py
- projects/swiftkv/train.py
Recent #18 introduces circular import statements. This PR reverts import-lated changes in #18 to solve `ImportError`.
ImportError message: https://app.readthedocs.org/api/v2/build/26864384.txt
> Partially revert #18 to solve circular import

- docs/conf.py
This PR allows docs to be generated without actually installing the library thus fixes readthedocs build errors.
> Fix readthedocs build

- README.md
- docs/quick-start.rst
- projects/mlp_speculator/llama-8b.yaml
- projects/swiftkv/swiftkv-llama-405b.yaml
- projects/swiftkv/swiftkv-llama-70b.yaml
- projects/swiftkv/swiftkv-llama-8b.yaml
The names were recently updated on HuggingFace from `meta-llama/Meta-Llama-*` to `meta-llama/Llama-*`: https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct/commit/38ff4e01a70559264c95945aa04b900a11e68422
> Update meta model names

- arctic_training/config/model.py
By default we had flash attention for `attn_implementation`. However, if the user did not have this installed it would result in an error. Adding flash attention as a dependency has its own headaches, so making the default `sdpa` to avoid seeing errors when first trying to library. @sfc-gh-sbekman
> Change to sdpa as default attn_implementation

- arctic_training/data/sft_factory.py
- arctic_training/data/source.py
With some data loading configurations, it's possible to filter out all of the dataset during data loading. This leads to ambiguous error messages later. Adding checks here that raise more descriptive errors when we encounter this problem.
> Improve data loading error message

- arctic_training/config/scheduler.py
- arctic_training/config/trainer.py
- projects/mlp_speculator/llama-8b.yaml
- projects/swiftkv/swiftkv-llama-405b.yaml
- projects/swiftkv/swiftkv-llama-70b.yaml
- projects/swiftkv/swiftkv-llama-8b.yaml
Since launch we had `optimizer.learning_rate` and `scheduler.learning_rate`. Fully deprecating `scheduler.learning_rate` and adding an error message if a user attempts to set this config field.
> full deprecate scheduler.lr setting

- arctic_training/data/factory.py
- arctic_training/data/source.py
when datasets/pyarrow that created the cache and loading the cache is incompatible we need to know the path to wipe out.
> info log the caching path

- .github/workflows/formatting.yaml
- .github/workflows/unit_tests.yaml
Setting up the python environment & dependency install for formatting and unit test workflows took a considerable amount of time (> 50% of total workflow time). Caching the environments speeds up unit test feedback for better development!
```
Formatting:   40s --> 20s
Unit-tests: 2m30s --> 58s
```
Cached environments can be seen under the repo "Actions" tab --> "Management" --> "Caches". If necessary, we can remove cached environments to force a new environment build.
For unit tests, we check the latest torch and deepspeed version and trigger a new environment build if they are updated from the cached versions.
> Use cached environment in actions workflows

- .github/workflows/unit_tests.yaml
- tests/conftest.py
We need to ensure we are still installing the latest checked out version of ArcticTraining even when using a cached environment.
> Fix error with unit test env caching

- arctic_training/config/data.py
- arctic_training/data/factory.py
- arctic_training/data/source.py
- tests/checkpoint/__init__.py
- tests/checkpoint/test_ds_engine.py
- tests/checkpoint/test_hf_engine.py
- tests/data/__init__.py
- tests/data/test_sft_factory.py
- tests/data/test_source.py
- tests/data/utils.py
This PR addresses two issues:
1. In some cases we were calculating the cache path incorrectly and over-writing an existing cache
2. Some of the field values used to calculate the hash path were not necessary
Additionally, cleaning up the cache path code to be easier to read and understand
> Fix cache path collision

- arctic_training/checkpoint/hf_engine.py
Quick test to compare outputs with zero2 / zero3:
```yaml
type: sft
code: ./tests/helpers.py
micro_batch_size: 1
deepspeed:
zero_optimization:
stage: 2
model:
name_or_path: Felladrin/Llama-160M-Chat-v1
peft_config:
peft_type: Lora
lora_alpha: 0.125
lora_dropout: 0.1
r: 8
bias: none
task_type: CAUSAL_LM
target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj
data:
sources:
- HuggingFaceH4/ultrachat_200k-truncated
use_data_cache: false
max_length: 2048
checkpoint:
type: huggingface
output_dir: ./llama-zero2-lora
save_end_of_training: true
```
```yaml
type: sft
code: ./tests/helpers.py
micro_batch_size: 1
deepspeed:
zero_optimization:
stage: 3
model:
name_or_path: Felladrin/Llama-160M-Chat-v1
peft_config:
peft_type: Lora
lora_alpha: 0.125
lora_dropout: 0.1
r: 8 …
```
> Add ZeRO3 checkpoint support for PEFT models

- arctic_training/data/factory.py
`.cpu().item()` and `.item()` do the same thing as at the end a pure python number is returned by `item()`
> remove redundant code

- CONTRIBUTING.md
- Makefile
- pyproject.toml
1. Start encapsulating complex workflow things into simple `Makefile` targets that can run out of the box.
Added:
- `make format`
- `make test`
- `make test-cpu`
- `make test-gpu`
This `Makefile` sports also an automatic `make help` ;)
```
$ make help
Usage:
make <target>
help                    this help
test                    run cpu and gpu tests
test-cpu                run cpu-only tests
test-gpu                run gpu-only tests
format                  fix formatting
```
2. fix the outdated doc
3. add testing dependencies that make tests running experience better
> add Makefile

- arctic_training/config/trainer.py
- arctic_training/config/utils.py
- arctic_training/utils.py
- tests/config/test_trainer_config.py
`pyyaml` silently overwrites values in the config for duplicate keys. Adding a custom loader that errors when duplicate keys are detected in the input config. Resolves #85
> Error on yaml config duplicate keys

- arctic_training/config/data.py
- arctic_training/data/hf_source.py
- tests/data/test_hf_source.py
- tests/helpers.py
Allows loading of locally saved HF datasets. Example:
```yaml
data:
sources:
- type: huggingface # explicitly specify source type
name_or_path: /path/to/dataset-1
- /path/to-dataset-2 # also valid
```
To support this change, also added a pydantic validator for the `sources` and `eval_sources` fields that loads the correct config type for a given data source. Previously, we just defaulted to huggingface-hosted data sources.
> Allow local data files for huggingface data sources

- Makefile
- arctic_training/model/liger_factory.py
- older liger dropped `attn_implementation` arg
- while it at reworking `make format` to use python's native venv
> require `liger-kernel>=0.5.5`

- arctic_training/config/data.py
- arctic_training/data/factory.py
- arctic_training/data/sft_factory.py
- arctic_training/data/source.py
- arctic_training/data/utils.py
- pyproject.toml
- tests/data/utils.py
Previously we were pre-sharding loading datasets and saving to a cache file for each process. However, this is more cumbersome and error-prone than loading/processing data with a single process and using the DistributedSampler. Switching to use the DistributedSampler in this PR, which simplifies data loading and makes it more readable.
Other changes:
- Caching of datasets is now the default and only behavior supported
- Helper functions to detect local/shared filesystem to determine which ranks should load/process data
> Switch to DistributedSampler

- arctic_training/config/base.py
- arctic_training/config/utils.py
- arctic_training/data/source.py
With the move to using distributed sampler, we want each rank to calculate the same cache path for a given data source. However a recent change in #102 that changed `local_rank`, `global_rank`, and `world_size` to being Pydantic computed_fields meant that these values were being included in the args that determine the cache path for a given data source. Reverting these changes and making those fields with `exclude=True` so they do not pollute the cache path args.
> Fix for cache path arg included values

- .github/workflows/unit_tests.yaml
- arctic_training/callback/mixin.py
- arctic_training/config/data.py
- arctic_training/data/factory.py
- arctic_training/data/hf_source.py
- arctic_training/data/source.py
- tests/data/test_sft_factory.py
- tests/data/test_source.py
- tests/helpers.py
- tests/trainer/test_sft_trainer.py
Add support for user-passed split value in data sources. This allows greater flexibility to control which split (if there are multiple splits in a dataset) and how much data is returned from each data source. For `HFDataSource` the split supports [slice splits](https://huggingface.co/docs/datasets/en/loading#slice-splits):
```yaml
data:
sources:
- HuggingFaceH4/ultrachat_200k:train[:20]
- type: huggingface
name_or_path: Open-Orca/SlimOrca
split: test[10:50]
```
> Add support for user-passed data splits

- arctic_training/trainer/dpo_trainer.py
Generally it's better to do `if x is not None` rather than `if x`. Small change to fix this in latest DPO release.
> Update DPO liger loss check

- arctic_training/config/logger.py
- arctic_training/metrics.py
- arctic_training/trainer/trainer.py
- arctic_training/utils.py
- Move output log files to a `logs/` subdir
- Ensure only global rank 0 is logging to W&B / printing
- Remove `step` and `epoch` from W&B reported values to avoid plots like step vs step
- Move `epochs` to end of logging line
- Reduce precision to more reasonable values for reported times
- Add human-readable formatting util functions
> Small improvements / fixes for metrics logging

- arctic_training/model/liger_factory.py
The liger model factory `create_model` method was missing a return type annotation which triggered a warning in the callback system. Adding the return type annotation to silence warning.
> Fix for Liger model callback warning

- arctic_training/metrics.py
I realized seqlen total per iteration is a useless metric, so switching to report the average seqlen, which is meaningful. 
later seen_tokens will be ~ `seqlen_total*iterations` and then it'd be meaningful again.
cc: @sfc-gh-mwyatt
>  metrics: seqlen report

- arctic_training/metrics.py
- arctic_training/utils.py
Changing the secs format to do `%H:%M:%S` when it's more than 1 minute - e.g. 1M+ ulysses is ~3h step.
Here are examples of output after the change:
`<1min`:
```
iter:  1/50   2% | loss: 6.9812 | iter time: 40.219s | iter tflops: 2.8 | lr: 4.167E-07 | seqlen: 7.71K | step time: 38.539s | step tflops: 2.9 | epoch: 0
iter:  2/50   4% | loss: 7.0292 | iter time: 6.913s | iter tflops: 15.2 | lr: 8.333E-07 | seqlen: 7.42K | step time: 6.898s | step tflops: 15.3 | epoch: 0
iter:  3/50   6% | loss: 7.2154 | iter time: 7.107s | iter tflops: 15.3 | lr: 1.250E-06 | seqlen: 7.58K | step time: 7.062s | step tflops: 15.4 | epoch: 0
```
`>1min`:
```
iter:  1/50   2% | loss: 8.2158 | iter time: 0:02:35 | iter tflops: 302.4 | lr: 1.000E-06 | seqlen: 249.18K | step time: 0:02:31 | step tflops: 309.3 | …
```
> metrics: better seconds formatting

- arctic_training/checkpoint/engine.py
- arctic_training/trainer/trainer.py
Fix two bugs causing multi-epoch training to fail:
- iter timer doesn't get stopped after the epoch which causes the start of the next epoch to crash
- if save_every_n_epochs is set, will start to save a checkpoint every step after the first epoch
> fix multi-epoch training

- arctic_training/trainer/trainer.py
our min required transformers version no longer requires this workaround
cc: @sfc-gh-mwyatt
> HfDeepSpeedConfig import

- .pre-commit-config.yaml
By default pre-commit runs the pre-commit hooks on multiple parallel processes (https://pre-commit.com/#hooks-require_serial). Setting `require_serial` to true for our license check hook to prevent the adding of the license text multiple times to newly added files.
> Fix for license check hook adding multiple license

- arctic_training/config/trainer.py
- arctic_training/trainer/trainer.py
- pyproject.toml
@sfc-gh-mwyatt, let's make this configurable?
3 settings:
1. at which level to bracket the profiling - at the moment I added "e2e" (all of it) vs "step" - only around the step
2. how many items to store - currently between 100k and 1m (hardcoded at the moment) `torch.cuda.memory._record_memory_history(max_entries=100_000)`
3. where to save the results 
Actually probably should `s/step/epoch/` as it's measuring at the level of epoch.
we can discuss the naming next and/or feel free to push directly into this PR.
> an optional mem profiler

- arctic_training/config/checkpoint.py
- arctic_training/config/optimizer.py
- arctic_training/config/trainer.py
- arctic_training/config/utils.py
- arctic_training/data/dpo_factory.py
- arctic_training/data/sft_factory.py
- arctic_training/scheduler/hf_factory.py
- docs/config.rst
- tests/config/test_config_custom_types.py
Added `HumanInt` and `HumanFloat` types for the pydantic configs. Allows parsing human-friendly strings to `int` or `float` values. The following formats are supported:
- `1_000` --> `1000`
- `50%` --> `0.5`
- `1e-3` --> `0.001`
- `2^10` --> `1024`
- `4K` --> `4000` (also `M`, `B`, and `T`)
- `4Ki` --> `4096` (also `Mi`, `Gi`, and `Ti`)
> Human-friendly number parsing

- arctic_training/config/data.py
- arctic_training/data/dpo_factory.py
- arctic_training/data/sft_factory.py
`max_length` is a value that is used by all `DataFactory` subclasses. As such, moving the field to the base `DataConfig` class.
resolves #160
> Move `max_length` to base `DataConfig`

- arctic_training/config/trainer.py
- arctic_training/trainer/trainer.py
Allow user to manually set `early_stop=True` during training by creating a file. Defaults to `/tmp/at_kill_switch`, but can be modified with `kill_switch_path` in the trainer config.
Resolves #126
> Add early exit kill switch

- pyproject.toml
wheels were being built with `py2-py3` label, but this was incorrect.
> Fix for python wheel builds

- arctic_training/data/factory.py
- arctic_training/data/source.py
Resolves #172 
Write to `{cache_path}.incomplete` and rename after saving all data is complete.
> Avoid corrupted data cache

- tests/conftest.py
allow having multiple repository checkouts and not needing to remember to rerun 'pip install -e .[dev]' when switching between checkouts and running tests.
> self contained tests

- arctic_training/model/liger_factory.py
- arctic_training_cli.py
make possible to run w/o the executable launcher
```
python -m arctic_training_cli x.yml
```
@sfc-gh-mwyatt
> enabled python -m arctic_training_cli

- arctic_training/scheduler/hf_factory.py
Currently using Nx sequence parallel the lr scheduler will advance Nx too fast, hitting lr=0 after 1/N of the training. This PR fixes that.
> fix lr scheduler for sequence parallel

- arctic_training/config/trainer.py
When using multiple workers on the torch `DataLoader` object, if a user has custom data classes defined in their projects `train.py`, we would get an import error like `ModuleNotFoundError: No module named 'custom_trainer'` from the spawned child processes.
Fixing that by making sure that the custom user objects are importable to child processes. This is achieved by creating a temporary directory in `/tmp/` and then creating a symlink to the users custom objects script (e.g., `/tmp/user_trainer_symlinks/user_train_828a1303.py` --> `./train.py`). This unique name is to avoid any potential conflicts with other modules.
> Fix custom code import error

- pyproject.toml
The license file entry in `pyproject.toml` was causing failures on install when using some versions of hatchling.
> Fix malformed pyproject.toml

- arctic_training/__init__.py
- arctic_training/data/hf_instruct_source.py
- docs/Makefile
- docs/usage.rst
- projects/sequence-parallelism/README.md
- projects/sequence-parallelism/run-sp1-llama-8b-baseline.yml
- projects/sequence-parallelism/run-sp1-llama-8b.yml
- projects/sequence-parallelism/run-sp1-qwen3-32b.yml
- projects/sequence-parallelism/run-sp16-llama-70b.yml
- projects/sequence-parallelism/run-sp16-llama-8b.yml
- projects/sequence-parallelism/run-sp16-qwen3-32b.yml
- projects/sequence-parallelism/run-sp32-llama-70b.yml
- projects/sequence-parallelism/run-sp32-llama-8b-baseline.yml
- projects/sequence-parallelism/run-sp32-llama-8b.yml
- projects/sequence-parallelism/run-sp32-qwen3-32b.yml
- projects/sequence-parallelism/run-sp64-llama-70b.yml
- projects/sequence-parallelism/run-sp64-qwen3-32b.yml
- projects/sequence-parallelism/run-sp8-llama-70b.yml
- projects/sequence-parallelism/run-sp8-llama-8b-no-mlp-no-act-offload.yml
- projects/sequence-parallelism/run-sp8-llama-8b-no-ulysses-no-liger-no-extras.yml
- projects/sequence-parallelism/run-sp8-llama-8b-no-ulysses-yes-liger-no-extras.yml
- projects/sequence-parallelism/run-sp8-llama-8b-yes-act-offload.yml
- projects/sequence-parallelism/run-sp8-llama-8b-yes-mlp.yml
- projects/sequence-parallelism/run-sp8-llama-8b.yml
- projects/sequence-parallelism/run-sp8-qwen3-32b.yml
Subclass the `HFDataSource` to `HFInstructDataSource` that supports the most common formats of instruct datasets:
1. Single column containing conversation examples in the form of a list of dicts
2. Multiple columns, each with the content for user, assistant, etc.
The `role_mapping` dict indicates how to locate the role and content within the dataset structure. We accept two types of inputs:
1. `{role_name} : {column_name}`
2. `{role_name} : {column_name.filter_field.filter_value}`
Additionally `content_field` can be used when a deep structure with complex columns is used and the value name needs remapping, see example 5 below for such a use-case.
Examples:
1. Dataset structure:
```python
{"user": "What is the capital of France?", "assistant": "The capital of France is Paris."}
```
Config: …
> Generalize support for instruct datasets

- arctic_training/trainer/trainer.py
- pyproject.toml
- tests/trainer/test_ulysses_alst.py
This PR:
1. syncs with transformers>=4.53 masking utils changes
2. updates the tests to also test for sdpa and not just fa2
3. complete the rename from ulysses-plus to ulysses-alst
> [ALST] sync with transformers>=4.53 masking utils changes

- scripts/download_data.py
Helpful script to parse a training config and download all the required data or model weights from HF, helpful especially in preparing prod training environments. 
I would use `arctic_training process-data config.yaml` for downloading data sources but this requires a pre-defined tokenizer and additional processing time that is not always needed or transferable across models.
> Artifact download script

- arctic_training/config/model.py
- arctic_training/trainer/trainer.py
- pyproject.toml
adding FA3 support
If you want to try FA3 you have to build it manually.
```
git clone https://github.com/Dao-AILab/flash-attention
cd flash-attention/hopper
pip install . --no-build-isolation --no-clean
```
then copy the built wheel.
> add FA3 support

- arctic_training/debug.py
Currently if I run `CUDA_VISIBLE_DEVICES=2 arctic_training ...` the memory usage in metrics logs is reported for gpu0 and not gpu2, so adding some logic to figure the device id from the env vars.
> report the correct device in pynvml

- arctic_training/trainer/trainer.py
This prevents from recreating a tqdm object twice an evaluation iter.
> Extract eval log iter condition

- .isort.cfg
In the case we have a local `./wandb/`, isort would incorrectly assume that `import wandb` should be part of local library imports rather than third-party imports.
> Fix: Make isort see `wandb` as third party

- arctic_training/data/hf_instruct_source.py
In `HFDataSourceInstruct`, in some cases where messages are stored as an ordered list of interleaved `user` and `assistant` we were destroying the ordering and putting all `user` at the beginning follow by all `assistant`.
> Bug fix: reordering of SFT dataset chats

- arctic_training/trainer/trainer.py
I'm getting:
```
File "/code/users/stas/github/DeepSpeed/deepspeed/runtime/zero/linear.py", line 116, in zero3_linear_wrap
return LinearFunctionForZeroStage3.apply(input, weight)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/autograd/function.py", line 576, in apply
return super().apply(*args, **kwargs)  # type: ignore[misc]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           [rank0]: RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
```
when mixing train+eval with zero3 enabled.
After researching this issue I propose to replace `torch.inference_mode` with `torch.no_grad` which removes the problem.
This is what other …
> [eval] replace `torch.inference_mode` with `torch.no_grad`

- arctic_training/data/sft_factory.py
Allows enabling loss mask on empty <think> tags to retain thinking ability for SFT without CoT traces. This is analogous to `--loss_scale ignore_empty_think` in ms-swift.
> Allow masking empty think tokens preventing the loss of thinking ability

- arctic_training/scheduler/hf_factory.py
Expose `scheduler_specific_kwargs`, such as `min_lr_rate` of the `cosine_with_min_lr` scheduler.
Enables config such as:
```
scheduler:
name: cosine_with_min_lr
warmup_ratio: 0.05
scheduler_specific_kwargs:
min_lr_rate: 0.1
```
> Expose scheduler-specific kwargs, such as min_lr_rate

- arctic_training/entrypoint.py
- arctic_training_cli.py
This PR will allow you to add to the launcher `--python_profile <sortkey>`, which will run the code under `cProfile`, where sort keys are `tottime` or `cumtime` and then at the end of the run it will dump to stdout something like:
```
2864954 function calls (2783834 primitive calls) in 6.499 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
515/18    0.002    0.000    3.857    0.214 parameter_offload.py:300(_post_forward_module_hook)
290    0.001    0.000    2.951    0.010 autocast_mode.py:512(decorate_fwd)
10    0.000    0.000    2.863    0.286 loss_utils.py:35(LigerForCausalLMLoss)
10    0.000    0.000    2.862    0.286 loss_utils.py:9(fixed_fused_linear_cross_entropy)
10    0.000    0.000    2.862    0.286 …
```
> add python profiler
