pyproject.toml
Added URLs and license file for PyPI page
=> Add project metadata for PyPI

arctic_training/config/enums.py, arctic_training/config/model.py, arctic_training/config/trainer.py, tests/config/test_model_config.py
=> fix dtype pydantic field

.github/workflows/formatting.yaml, .pre-commit-config.yaml, arctic_training/callback/wandb.py, arctic_training/config/wandb.py
Adds `entity` and `name` to help identify the W&B run.
=> add additional W&B args

tests/checkpoint/test_ds_engine.py, tests/checkpoint/test_hf_engine.py, tests/conftest.py, tests/trainer/test_sft_trainer.py
Reducing the size of the CI model to improve unit test time.
=> Move to smaller CI model

arctic_training/optimizer/adam_factory.py, arctic_training/trainer/sft_trainer.py
cherry pick from #89, see usage in the original PR
=> cpu adam support

arctic_training/config/trainer.py, arctic_training/trainer/trainer.py
adds trainer level config:
```yaml
step_timer: [true|false]
```
=> add basic step timer

arctic_training/synth/__init__.py, arctic_training/synth/callers.py, arctic_training/synth/test_multi_replica_vllm_caller.py, arctic_training/synth/vllm_callers.py, arctic_training/synth/vllm_utils.py
There will be 4 PRs along this line: i) Support multi-replica + TP generation within a node, ii) Support Generation Checkpointing to allow for efficient resume when replica's fail, which seems to happen once in a while, iii) Support auto-resume when a replica fails, and iv) Support multi-replica across multiple nodes.
=> Multi-Replica Generation (PR 1/4)

arctic_training/cli.py
=> Add help message about DeepSpeed args to ArcticTraining launcher

arctic_training/synth/vllm_callers.py
=> fix caller import

arctic_training/config/data.py, arctic_training/data/factory.py
Users can now override the cache filesystem type if ArcticTraining is not detecting it correctly. The file system type determines which ranks will download and process the data (i.e., local: all local rank 0; shared: only global rank 0). If we detect this incorrectly, then some processes will have no data and training will break.
Defaults to `auto` and keeps current behavior unless user specifies `local` or `shared`
Resolves #87
=> Add `cache_fs_type` field

arctic_training/trainer/trainer.py
also needs local_rank
should this property be cached and not recalculated every call?
cc: @sfc-gh-mwyatt
=> another multi-node rank issue

arctic_training/utils.py
when working with seqlen>1M, at least one more decimal is wanted - later perhaps will make it configurable.
cc: @sfc-gh-mwyatt
=> human_format_base2_number change to 2 decimals

pyproject.toml
This PR:
- add myself as a co-author
- specify the project is in Beta
- add supported python versions
=> project: authors + stableness + py versions

.github/workflows/docs.yaml, .github/workflows/formatting.yaml, .readthedocs.yaml, arctic_training/config/enums.py, arctic_training/config/model.py, arctic_training/model/hf_factory.py, arctic_training/model/liger_factory.py, docs/conf.py, scripts/install_deps.py, tests/config/test_model_config.py, tests/helpers.py, tests/model/test_hf_factory.py
Various changes to the code has caused warnings to surface in the docs build. Added fixes to address these and have properly building docs again. Also adding a unit test that builds the docs to avoid this problem moving forward.
=> Fix ReadTheDocs build and add unit test

arctic_training/config/trainer.py
Followup to #166 that extends human-friendly numerical parsing functionality to DeepSpeed configs. Since the DeepSpeed config is defined in that library we cannot use `HumanInt` and `HumanFloat` as types to automatically handle parsing. Instead we must do a try...except with each field passed by the user in the config dict. The `HumanInt` and `HumanFloat` should likely be added to DeepSpeed. Will follow up in the future with a PR over there.
Resolves #165
=> Human friendly values for DeepSpeed config

arctic_training/config/data.py, arctic_training/data/dpo_factory.py, arctic_training/data/factory.py, arctic_training/data/sft_factory.py
Fixes: https://github.com/snowflakedb/ArcticTraining/issues/176
=> add `data.config.dl_num_workers`

Makefile, arctic_training/debug.py
Prep for Ulysses PR:
1. fix Makefile
2. add extended debug functionality + nvml device id fix
=> pre-Ulysses PR features

arctic_training/config/trainer.py, arctic_training/trainer/trainer.py, arctic_training/utils.py
moving the Ulysses PR changes wrt GAS and metrics to a standalone PR to simplify the former
@sfc-gh-mwyatt
=> more GAS support + metrics-to-file logging

projects/sequence-parallelism/README.md, projects/sequence-parallelism/USAGE.md
The project has been renamed at the last moment, so this PR is adapting to that change.
There are no code changes in this PR, just docs.
=> s/UlyssesPlus/Arctic Long Sequence Training (ALST)/

projects/arctic_lstm_speculator/speculator/data_generation/concat_generated_datasets.py
This enables generating data longer than 256 length
=> Remove unnecessary assertion

README.md, projects/sequence-parallelism/README.md
1. add ALST paper reference
2. start papers section on the front page
=> add ALST paper reference

arctic_training/config/trainer.py, tests/config/test_trainer_config.py
If a user has a `train.py` with a relative import:
```python
from my_local_util import my_custom_util_func
...
```
Then this import would fail as only the `train.py` is symlinked to the custom module directory. Instead creating a symlink for the entire directory where the custom code is located. This fixed the problem and allows relative imports.
Added a test to verify this functionality.
@sfc-gh-prenc this is a follow up to the problem we fixed in #204
=> Fix for custom user script relative import

CONTRIBUTING.md
CONTRIBUTING.md: add first-good-issue link
=> CONTRIBUTING.md: add first-good-issue link

arctic_training/trainer/trainer.py
I missed this condition when adding FA3 support
=> FA3 support: fix tflops
